
# Настройки кухни
kitchen.capacity=1
kitchen.timeout=10000

#меню пицц
pizza.margarita.name=Margarita
pizza.margarita.price.small=100
pizza.margarita.price.medium=200
pizza.margarita.price.large=300

addspring.liquibase.enabled=true
spring.liquibase.change-log=/db-changelog/db.changelog.xml

spring.datasource.url=jdbc:postgresql://localhost:5432/pizzadb
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true